generator_kind: fixed_no_rand

mask_generator_kwargs:


max_masks_per_image: 1

cropping:
  out_min_size: 72
  handle_small_mode: upscale
  out_square_crop: True
  crop_min_overlap: 1

max_tamper_area: 1.0
